'use client'
import { SessionProvider } from 'next-auth/react'
import '../globals.css'
import Image from 'next/image'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className='container'>
          <div className='relative w-20 h-20'>
            <Image
              src={"/logo.svg"}
              fill
              alt='logo'
            />
          </div>
          {children}
        </body>
      </SessionProvider>
    </html>
  )
}
