'use client'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import LeftSidebar from '@/components/LeftSidebar'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex relative max-h-screen overflow-hidden`}>
        <SessionProvider>
          <LeftSidebar />
          <main className='w-full relative'>
            <Header />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
